### PR TITLE
Retrieves View informations

### PR DESCRIPTION
**Pull request by bltavares**
Hello there.

I've been using this package to retrieve some job informations on a bot, but it happen that we needed to include a view information on the bot as well.

This PR introduces the `view_info` method to query Jenkins about views.

### CODE REVIEW

**Comment by roberto** [comment]
:+1:

**Comment by rogeriochaves** [comment]
:+1:

**Comment by jansepar** [comment]
I just merged a previous PR that does the same thing called `all_jobs_in_view` - but then I saw this PR which attempts to do the same thing. I've actually moved away from using Jenkins, so I'm not entirely sure if `all_jobs_in_view` is a more appropriate name then what you've called it (`view_info`). Please advise! If you prefer it to be `view_info` please feel free to pull the latest from master and modify this PR to have a `view_info` alias method.

**Comment by bltavares** [comment]
Hey @jansepar,that other commit solves it for me already and I'm happy with the other name. Thanks for taking a look on this (:

This is closed by #32

**Pull request closed without merging**
